# Generated by Django 3.1.7 on 2022-05-19 19:27

import datetime
from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='activation_key',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 20, 19, 27, 22, 540010)),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='address',
            field=models.CharField(blank=True, max_length=256, verbose_name='Адрес доставки'),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='phone',
            field=models.IntegerField(null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='age',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='возраст'),
        ),
    ]
