# Generated by Django 5.2.7 on 2026-04-08 01:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_alter_shopuser_activation_key_expires_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 9, 1, 15, 59, 720371, tzinfo=datetime.timezone.utc)),
        ),
    ]
