# Generated by Django 5.2.7 on 2026-04-08 01:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_alter_shopuser_activation_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 9, 1, 25, 47, 881531, tzinfo=datetime.timezone.utc)),
        ),
    ]
