# Generated by Django 4.2.30 on 2026-05-15 20:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_alter_shopuser_activation_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 16, 20, 28, 51, 437115, tzinfo=datetime.timezone.utc)),
        ),
    ]
