# Generated by Django 5.2.7 on 2026-04-08 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='имя')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
            },
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'бренд', 'verbose_name_plural': 'бренды'},
        ),
        migrations.AddField(
            model_name='product',
            name='image_2',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='products_images', verbose_name='фото-2'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_3',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='products_images', verbose_name='фото-3'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_4',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='products_images', verbose_name='фото-4'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_5',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='products_images', verbose_name='фото-5'),
        ),
        migrations.AddField(
            model_name='product',
            name='interior',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='интерьер'),
        ),
        migrations.AddField(
            model_name='product',
            name='lighting_area',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='площадь освещения'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='цена cо скидкой'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.BooleanField(blank=True, null=True, verbose_name='Акция'),
        ),
        migrations.AddField(
            model_name='product',
            name='style',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='стиль'),
        ),
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='артикул'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.productcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='цвет'),
        ),
        migrations.AlterField(
            model_name='product',
            name='descriptions',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='diameter',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='диаметр'),
        ),
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='высота'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='products_images', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='lamps',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='количество ламп'),
        ),
        migrations.AlterField(
            model_name='product',
            name='lamps_type',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='цоколь'),
        ),
        migrations.AlterField(
            model_name='product',
            name='length',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='длина'),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='метериал'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=256, null=True, verbose_name='имя продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='power',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='мощность'),
        ),
        migrations.AlterField(
            model_name='product',
            name='series',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='серия'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_desc',
            field=models.CharField(blank=True, max_length=64, verbose_name='краткое описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='размер'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='вес'),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='ширина'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.producttype'),
        ),
        migrations.CreateModel(
            name='ProductType_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='имя')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('parent_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.producttype', verbose_name='основной тип')),
            ],
            options={
                'verbose_name': 'Подтип',
                'verbose_name_plural': 'подтипы',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='type_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.producttype_2', verbose_name='подтип'),
        ),
    ]
