# Generated by Django 5.2.7 on 2026-04-08 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_producttype_alter_productcategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='diameter',
        ),
        migrations.RemoveField(
            model_name='product',
            name='height',
        ),
        migrations.RemoveField(
            model_name='product',
            name='interior',
        ),
        migrations.RemoveField(
            model_name='product',
            name='lamps',
        ),
        migrations.RemoveField(
            model_name='product',
            name='lamps_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='length',
        ),
        migrations.RemoveField(
            model_name='product',
            name='lighting_area',
        ),
        migrations.RemoveField(
            model_name='product',
            name='material',
        ),
        migrations.RemoveField(
            model_name='product',
            name='power',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='style',
        ),
        migrations.RemoveField(
            model_name='product',
            name='width',
        ),
    ]
