# Generated by Django 5.2.7 on 2026-04-08 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_product_color_remove_product_diameter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='descriptions',
        ),
        migrations.AddField(
            model_name='product',
            name='igredients',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Состав'),
        ),
    ]
