# Generated by Django 4.2.30 on 2026-05-15 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_product_descriptions_product_igredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='logo',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='products_images', verbose_name='логотип'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_desc',
            field=models.CharField(blank=True, max_length=200, verbose_name='краткое описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.producttype_2', verbose_name='подтип'),
        ),
    ]
